config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #To read all the tasks
  get "tasks", to: "tasks#index"

  #To create a task
  get "tasks/new", to: "tasks#new"

  #To read a task
  get "tasks/:id", to: "tasks#show", as: "task"

  post "tasks", to: "tasks#create"

  get 'tasks/:id/edit', to: 'tasks#edit', as: "edit"

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    Task.create(task_params)
    redirect_to tasks_path
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title, "Name of task : " %>
  <%= f.text_field :title %>

  <%= f.label :details, "Details of task : "%>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
<p><%= link_to "<= back", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <h2><%= check_box_tag(task.title, task.title, task.completed) %> <%= link_to task.title, task_path(task) %> <%= link_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" }  %></h2>
<% end %>

<p><%= link_to "Add a new task", tasks_new_path %></p>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Name of task : " %>
    <%= f.text_field :title, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :details, "Details of task : " %>
    <%= f.text_field :details, class: 'form-control'  %>
   </div>

  <%= f.submit "Create a task",  class: 'btn btn-primary' %>
<% end %>
<p><%= link_to "<= back", tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<h2><%= link_to "Edit", edit_path %></h2>
<p><%= link_to "<= back", tasks_path %></p>